config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'account' }
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Subco App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
 end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Subco App</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark navbar-nav">
	<div class="container-fluid">
		<%= link_to "Subco App", root_path, id: "logo" %>
		<nav>
			<ul class="navbar-nav">
				<li class="nav-item"><%= link_to "Home", root_path %></li>
				<li class="nav-item"><%= link_to "About", about_path %></li>
					<% if current_user %>
						<li><%=link_to "Account", edit_user_registration_path %></li>
						<li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%=link_to "Sign Up", new_user_registration_path %></li>
						<li><%=link_to "Login", new_user_session_path %></li>
					<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= full_title(yield(:title)) %></title>
	  <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= render 'layouts/shim' %>
  </head>
  <body>
	  <%= render 'layouts/header' %>
	  <div class="container">
		  <p class="notice"><%= notice %></p>
		  <p class="alert"><%= alert %></p>
		  <%= yield %>
		  <%= render 'layouts/footer' %>
	  </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to Subco App</h1>
	<h2>
		This is the home page.
	</h2>

	<% if current_user %>
	<% else %>
		<%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
	<% end %>
</div>